blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using retryablehttp
    url: https://github.com/khulnasoft-lab/retryablehttp/discussions/categories/q-a
    about: Ask a question or request support for using retryablehttp

  - name: Share idea / feature to discuss for retryablehttp
    url: https://github.com/khulnasoft-lab/retryablehttp/discussions/categories/ideas
    about: Share idea / feature to discuss for retryablehttp

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/khulnasoft-lab
    about: Connect with PD Team for direct communication